export const FETCH_USER = "FETCH_USER";
export const FETCH_EXPLORE_QUOTES = "FETCH_EXPLORE_QUOTES";
export const SAVE_QUOTE_TO_PROFILE = "SAVE_QUOTE_TO_PROFILE";
export const REMOVE_QUOTE_FROM_PROFILE = "REMOVE_QUOTE_FROM_PROFILE";

export const ADD_JOURNAL_ENTRY = "ADD_JOURNAL_ENTRY";
